FROM node:20-bookworm AS builder
WORKDIR /app
COPY . .
RUN yarn install && yarn build --no-dts

FROM node:20-bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    libfreetype6 fontconfig fonts-noto-cjk \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app .
ENV APP_ENV=production
EXPOSE 13000
CMD ["yarn", "start"]
